apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starter-kit.fullname" . }}
  annotations:
  {{- if and .Values.vcsInfo.repoUrl .Values.vcsInfo.branch }}
    app.openshift.io/vcs-ref: {{ .Values.vcsInfo.branch }}
    app.openshift.io/vcs-uri: {{ .Values.vcsInfo.repoUrl }}
  {{- end }}
  {{- if .Values.connectsTo }}
    app.openshift.io/connects-to: {{ .Values.connectsTo }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "starter-kit.name" . }}
    helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
    {{- if .Values.partOf }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    {{- end}}
    {{- if .Values.runtime }}
    app.openshift.io/runtime: {{ .Values.runtime }}
    {{- end}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "starter-kit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "starter-kit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.image.secretName }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
#           livenessProbe:
#             httpGet:
#               path: /
#               port: http
#           readinessProbe:
#             httpGet:
#               path: /
#               port: http
          env:
            - name: INGRESS_HOST
              value: ""
            - name: PROTOCOLS
              value: ""
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            # - name: CLIENT_CERT
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: CLIENT_CERT
            # - name: CLIENT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: CLIENT_KEY
            # - name: CLIENT_CA
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: CLIENT_CA
            # - name: DB_HOST
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: DB_HOST
            # - name: DB_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: DB_NAME
            # - name: DB_PASS
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: DB_PASS
            # - name: DB_PORT
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: DB_PORT
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: DB_USER
            - name: REACT_APP_API_KEY
              valueFrom:
                secretKeyRef:
                  key: REACT_APP_API_KEY
                  name: lauren-demo-api-key
            # - name: APP_ID_CLIENT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_CLIENT_ID
            # - name: APP_ID_TENANT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_TENANT_ID
            # - name: APP_ID_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_SECRET
            # - name: APP_ID_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_NAME
            # - name: APP_ID_OAUTH_SERVER_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_OAUTH_SERVER_URL
            # - name: APP_ID_PROFILES_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_PROFILES_URL
            # - name: APP_ID_DISCOVERY_ENDPOINT
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_DISCOVERY_ENDPOINT
            # - name: APP_ID_REDIRECT_URI
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_REDIRECT_URI
            # - name: APP_ID_TYPE
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: APP_ID_TYPE
            # - name: SESSION_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: lauren-demo
            #       key: SESSION_SECRET
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
